name: Streamlit Application

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest  #[ self-hosted ]

    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python 3.11
        uses: actions/checkout@v3
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up Google API Key
          env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          run: echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}" >> $GITHUB_ENV

      - name: Docker Build and push
        run: |
          docker build -t generativeai .
          docker tag generativeai xerxez786/genai:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push xerxez786/genai:latest

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      



  
  
